__builtin void * __dotdotdot__( void ) __attribute__((leaf));
__builtin void * __alloc ( __size_t );
__builtin void __free ( void * );
__builtin __codeptr __get_return_address ( void ) __attribute__((leaf,const));
__builtin void __enable( void ) __attribute__((leaf));
__builtin void __disable( void ) __attribute__((leaf));
__builtin int __disable_and_save( void ) __attribute__((leaf));
__builtin void __restore( int ) __attribute__((leaf));
__builtin void __dsync( void ) __attribute__((leaf));
__builtin void __isync( void ) __attribute__((leaf));
__builtin void __svlcx( void ) __attribute__((leaf));
__builtin void __rslcx( void ) __attribute__((leaf));
__builtin void __syscall(int);
__builtin void __bisr(const unsigned int) __attribute__((leaf));
__builtin void __nop( void ) __attribute__((leaf));
__builtin void __debug( void ) __attribute__((leaf));
__builtin int __mfcr(int) __attribute__((leaf));
__builtin void __mtcr(int, int) __attribute__((leaf));
__builtin int __clz(int) __attribute__((leaf,const));
__builtin int __clo(int) __attribute__((leaf,const));
__builtin int __cls(int) __attribute__((leaf,const));
__builtin signed char __satb ( int ) __attribute__((leaf,const));
__builtin unsigned char __satbu ( unsigned int ) __attribute__((leaf,const));
__builtin short __sath ( int ) __attribute__((leaf,const));
__builtin unsigned short __sathu ( unsigned int ) __attribute__((leaf,const));
__builtin float __fabsf( float f ) __attribute__((leaf,const));
__builtin double __fabs( double d ) __attribute__((leaf,const));
__builtin int __abss(int) __attribute__((leaf,const));
__builtin int __abs(int) __attribute__((leaf,const));
__builtin int __parity(int) __attribute__((leaf,const));
__builtin int __min(int,int) __attribute__((leaf,const));
__builtin unsigned int __minu(unsigned int,unsigned int) __attribute__((leaf,const));
__builtin short __mins(short,short) __attribute__((leaf,const));
__builtin int __max(int,int) __attribute__((leaf,const));
__builtin unsigned int __maxu(unsigned int,unsigned int) __attribute__((leaf,const));
__builtin short __maxs(short,short) __attribute__((leaf,const));
__builtin int __extr(int,int,int) __attribute__((leaf,const));
__builtin unsigned int __extru(int,int,int) __attribute__((leaf,const));
__builtin int __insert(int,int,int,int) __attribute__((leaf,const));
__builtin int __ins(int,int,int,int) __attribute__((leaf,const));
__builtin int __insn(int,int,int,int) __attribute__((leaf,const));
__builtin int __mulsc(int,int,int) __attribute__((leaf,const));
__builtin void __imaskldmst( int *,int,int,int) __attribute__((leaf));
__builtin void __ldmst( unsigned int *address, unsigned int mask, unsigned int value ) __attribute__((leaf));
#define __putbit(value,address,bitoffset) __imaskldmst(address,value,bitoffset,1)
#define __getbit(address,bitoffset) __extru(*(address),bitoffset,1)
__builtin unsigned int __swap( unsigned int *place, unsigned int value ) __attribute__((leaf));
__builtin unsigned int __rol( unsigned int value, unsigned int count ) __attribute__((leaf,const));
__builtin unsigned int __ror( unsigned int value, unsigned int count ) __attribute__((leaf,const));
__builtin long int __mulfractlong_ctri(__wrap __fract,long int) __attribute__((leaf,const));
__builtin __wrap __sfract __round16_ctri(__wrap __fract) __attribute__((leaf,const));
__builtin __wrap __fract __getfract_ctri(__wrap __laccum) __attribute__((leaf,const));
__builtin short __clssf_ctri(__wrap __sfract) __attribute__((leaf,const));
__builtin __wrap __sfract __shasfracts_ctri(__wrap __sfract,int) __attribute__((leaf,const));
__builtin __wrap __fract __shafracts_ctri(__wrap __fract,int) __attribute__((leaf,const));
__builtin __wrap __laccum __shaaccum_ctri(__wrap __laccum,int) __attribute__((leaf,const));
__builtin long int __mulfractlong(__fract,long int) __attribute__((leaf,const));
__builtin __sfract __round16(__fract) __attribute__((leaf,const));
__builtin __fract __getfract(__laccum) __attribute__((leaf,const));
__builtin short __clssf(__sfract) __attribute__((leaf,const));
__builtin __sfract __shasfracts(__sfract,int) __attribute__((leaf,const));
__builtin __fract __shafracts(__fract,int) __attribute__((leaf,const));
__builtin __laccum __shaaccum(__laccum,int) __attribute__((leaf,const));
__builtin __sfract __mac_sf( __sfract, __sfract, __sfract ) __attribute__((leaf,const)); /* returns ( a + b * c )*/
__builtin __sfract __mac_r_sf( __sfract, __sfract, __sfract ) __attribute__((leaf,const));
__builtin __sfract __u16_to_sfract( unsigned short integer ) __attribute__((leaf,const));
__builtin __sfract __s16_to_sfract( signed short integer ) __attribute__((leaf,const));
__builtin unsigned short int __sfract_to_u16( __sfract ) __attribute__((leaf,const));
__builtin signed short int __sfract_to_s16( __sfract ) __attribute__((leaf,const));
__builtin __circ void *__initcirc ( void *, unsigned short, unsigned short ) __attribute__((leaf));
__builtin __packb __initpackbl(long int) __attribute__((leaf,const));
__builtin __packhw __initpackhwl(long int) __attribute__((leaf,const));
__builtin __packb __initpackb(int,int,int,int) __attribute__((leaf,const));
__builtin unsigned __packb __initupackb(unsigned int,unsigned int,unsigned int,unsigned int) __attribute__((leaf,const));
__builtin __packhw __initpackhw(short int, short int) __attribute__((leaf,const));
__builtin unsigned __packhw __initupackhw(unsigned short int, unsigned short int) __attribute__((leaf,const));
__builtin char __extractbyte1(__packb) __attribute__((leaf,const));
__builtin unsigned char __extractubyte1(__packb) __attribute__((leaf,const));
__builtin char __extractbyte2(__packb) __attribute__((leaf,const));
__builtin unsigned char __extractubyte2(__packb) __attribute__((leaf,const));
__builtin char __extractbyte3(__packb) __attribute__((leaf,const));
__builtin unsigned char __extractubyte3(__packb) __attribute__((leaf,const));
__builtin char __extractbyte4(__packb) __attribute__((leaf,const));
__builtin unsigned char __extractubyte4(__packb) __attribute__((leaf,const));
__builtin short __extracthw1(__packhw) __attribute__((leaf,const));
__builtin unsigned short __extractuhw1(unsigned __packhw) __attribute__((leaf,const));
__builtin short __extracthw2(__packhw) __attribute__((leaf,const));
__builtin unsigned short __extractuhw2(unsigned __packhw) __attribute__((leaf,const));
__builtin char __getbyte1(__packb *) __attribute__((leaf));
__builtin char __getbyte2(__packb *) __attribute__((leaf));
__builtin char __getbyte3(__packb *) __attribute__((leaf));
__builtin char __getbyte4(__packb *) __attribute__((leaf));
__builtin short int __gethw1(__packhw *) __attribute__((leaf));
__builtin short int __gethw2(__packhw *) __attribute__((leaf));
__builtin unsigned char __getubyte1(unsigned __packb *) __attribute__((leaf));
__builtin unsigned char __getubyte2(unsigned __packb *) __attribute__((leaf));
__builtin unsigned char __getubyte3(unsigned __packb *) __attribute__((leaf));
__builtin unsigned char __getubyte4(unsigned __packb *) __attribute__((leaf));
__builtin unsigned short int __getuhw1(unsigned __packhw *) __attribute__((leaf));
__builtin unsigned short int __getuhw2(unsigned __packhw *) __attribute__((leaf));
__builtin __packb __insertbyte1(__packb,char) __attribute__((leaf,const));
__builtin unsigned __packb __insertubyte1(unsigned __packb,unsigned char) __attribute__((leaf,const));
__builtin __packb __insertbyte2(__packb,char) __attribute__((leaf,const));
__builtin unsigned __packb __insertubyte2(unsigned __packb,unsigned char) __attribute__((leaf,const));
__builtin __packb __insertbyte3(__packb,char) __attribute__((leaf,const));
__builtin unsigned __packb __insertubyte3(unsigned __packb,unsigned char) __attribute__((leaf,const));
__builtin __packb __insertbyte4(__packb,char) __attribute__((leaf,const));
__builtin unsigned __packb __insertubyte4(unsigned __packb,unsigned char) __attribute__((leaf,const));
__builtin __packhw __inserthw1(__packhw,short) __attribute__((leaf,const));
__builtin unsigned __packhw __insertuhw1(unsigned __packhw, unsigned short) __attribute__((leaf,const));
__builtin __packhw __inserthw2(__packhw,short) __attribute__((leaf,const));
__builtin unsigned __packhw __insertuhw2(unsigned __packhw, unsigned short) __attribute__((leaf,const));
__builtin void __setbyte1(__packb *,char) __attribute__((leaf));
__builtin void __setbyte2(__packb *,char) __attribute__((leaf));
__builtin void __setbyte3(__packb *,char) __attribute__((leaf));
__builtin void __setbyte4(__packb *,char) __attribute__((leaf));
__builtin void __sethw1(__packhw *,short) __attribute__((leaf));
__builtin void __sethw2(__packhw *,short) __attribute__((leaf));
__builtin void __setubyte1(unsigned __packb *,unsigned char) __attribute__((leaf));
__builtin void __setubyte2(unsigned __packb *,unsigned char) __attribute__((leaf));
__builtin void __setubyte3(unsigned __packb *,unsigned char) __attribute__((leaf));
__builtin void __setubyte4(unsigned __packb *,unsigned char) __attribute__((leaf));
__builtin void __setuhw1(unsigned __packhw *,unsigned short) __attribute__((leaf));
__builtin void __setuhw2(unsigned __packhw *,unsigned short) __attribute__((leaf));
__builtin __packb __absb(__packb) __attribute__((leaf,const));
__builtin __packhw __absh(__packhw) __attribute__((leaf,const));
__builtin __packhw __sat __abssh(__packhw __sat) __attribute__((leaf,const));
__builtin __packb __minb(__packb,__packb) __attribute__((leaf,const));
__builtin unsigned __packb __minbu(unsigned __packb,unsigned __packb) __attribute__((leaf,const));
__builtin __packhw __minh(__packhw,__packhw) __attribute__((leaf,const));
__builtin unsigned __packhw __minhu(unsigned __packhw,unsigned __packhw) __attribute__((leaf,const));
__builtin short int __add(short int, short int) __attribute__((leaf,const));
__builtin short int __sub(short int, short int) __attribute__((leaf,const));
__builtin short int __mult(short int, short int) __attribute__((leaf,const));
__builtin short int __div_s(short int, short int) __attribute__((leaf,const));
__builtin short int __mult_r(short int, short int) __attribute__((leaf,const));
__builtin int __L_mac( int, short int, short int) __attribute__((leaf,const));
__builtin int __L_macNs( int, short int, short int) __attribute__((leaf,const));
__builtin short int __mac_r( int, short int, short int) __attribute__((leaf,const));
__builtin short int __msu_r( int, short int, short int) __attribute__((leaf,const));
__builtin int __L_msu( int, short int, short int) __attribute__((leaf,const));
__builtin int __L_msuNs( int, short int, short int) __attribute__((leaf,const));
__builtin short int __abs_s(short int) __attribute__((leaf,const));
__builtin short int __negate(short int) __attribute__((leaf,const));
__builtin short int __round(int) __attribute__((leaf,const));
__builtin short int __shl(short int, short int) __attribute__((leaf,const));
__builtin short int __shr(short int, short int) __attribute__((leaf,const));
__builtin short int __shr_r(short int, short int) __attribute__((leaf,const));
__builtin short int __norm_s(short int) __attribute__((leaf,const));
__builtin int __L_add(int, int) __attribute__((leaf,const));
__builtin int __L_sub(int, int) __attribute__((leaf,const));
__builtin int __L_mult(short int, short int) __attribute__((leaf,const));
__builtin short int __extract_h(int) __attribute__((leaf,const));
__builtin short int __extract_l(int) __attribute__((leaf,const));
__builtin int __L_deposit_h(short int) __attribute__((leaf,const));
__builtin int __L_deposit_l(short int) __attribute__((leaf,const));
__builtin int __L_abs(int) __attribute__((leaf,const));
__builtin int __L_negate(int) __attribute__((leaf,const));
__builtin short int __norm_l(int) __attribute__((leaf,const));
__builtin int __L_shl(int, short int) __attribute__((leaf,const));
__builtin int __L_shr(int, short int) __attribute__((leaf,const));
__builtin int __L_shr_r(int, short int) __attribute__((leaf,const));
__builtin int __L_ror(int) __attribute__((leaf,const));
__builtin int __L_rol(int) __attribute__((leaf,const));
__builtin int __mpyuu(int, int) __attribute__((leaf,const));
__builtin int __mpyus(int, int) __attribute__((leaf,const));
__builtin int __mpysu(int, int) __attribute__((leaf,const));
__builtin unsigned char * __cacheawi_bo_post_inc( unsigned char *p ) __attribute__((leaf));
__builtin void __cacheawi( unsigned char *p ) __attribute__((leaf));
__builtin void __cacheiwi( unsigned char *p ) __attribute__((leaf));
__builtin void __cacheaw( unsigned char *p ) __attribute__((leaf));
__builtin void __cacheiw( unsigned char *p ) __attribute__((leaf));
__builtin void __cacheai( unsigned char *p ) __attribute__((leaf));
__builtin void __wait( void ) __attribute__((leaf));
__builtin unsigned int __crc32( unsigned int b, unsigned int a ) __attribute__((leaf,const));
__builtin unsigned int __cmpswapw( unsigned int *p, unsigned int value, unsigned int compare ) __attribute__((leaf));
__builtin unsigned int __swapmskw( unsigned int *p, unsigned int value, unsigned int mask ) __attribute__((leaf));
